modLoader="javafml" #mandatory

loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="MIT License"

issueTrackerURL="https://github.com/Darkosaur/Additional-Spawn-Eggs/issues" #optional

[[mods]] #mandatory

modId="ase" #mandatory

version="1.0.0-1.16.4" #mandatory

displayName="Additional Spawn Eggs" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="Credits go to Darkosaur for doing all of this." #optional

authors="Darkosaur" #optional

description='''
Additional Spawn Eggs is a mod that adds spawn eggs to vanilla Minecraft mobs that don't have them such as Iron Golems, Snow Golems, etc.
'''

[[dependencies.examplemod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[35,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
